# Generated by Django 4.1.4 on 2022-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('salesman', models.CharField(max_length=50)),
                ('items', models.CharField(max_length=50)),
                ('units', models.IntegerField()),
            ],
        ),
    ]
